name: CI - Test e Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installazione dipendenze
      run: npm install

    - name: Esecuzione test con coverage
      run: npm run test:coverage

    - name: Caricamento report coverage (solo per Node 20.x)
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/lcov-report
        retention-days: 5